server:
  port: 8989
spring:
  application:
    name: turbine
management:
  server:
    port: 8990


eureka:
  instance:
    ip-address: 192.168.98.22
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.98.22:8761/eureka/,http://192.168.98.23:8761/eureka/
turbine:
  app-config: hello-consumer
  cluster-name-expression: default
  combine-host-port: true





