server:
  port: 8088

spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 是否与服务发现组件进行结合，通过serviceId转发到具体的服务实例，默认false
          enabled: true
          # 当注册中心为Eureka时，设置为true表示开启用小写的serviceId进行基于服务路由的转发
          lowerCaseServiceId: true
      # 路由
      routes:
      - id: consumer1
        # 跳转的微服务地址 hello-cusumer为服务名称
        uri: lb://hello-consumer
        predicates:
        - Path=/test/**
#        filters:
#         name: Hystrix # Hystrix Filter的名称
#           # Hystrix配置参数
#            args:
#              # HystrixCommand的名字
#              name: fallbackcmd
#              fallbackUri: forward:/fallback # fallback对应的uri
      - id: consumer-1
        uri: lb://hello-consumer
        predicates:
        - Path=/consumer-1
#        filters:
#           name: Hystrix
#            args:
#              name: fallbackcmd2
#              fallbackUri: forward:/fallback
      - id: service1
        uri: lb://cloud-service-provide
        predicates:
        - Path=/producer
      - id: jd_route
        uri: http://jd.com/
        predicates:
        - Path=/jd/**

eureka:
  instance:
    #ip-address: 192.168.98.22
    prefer-ip-address: true
    #hostname: localhost
  client:
    serviceUrl:
      #defaultZone: http://192.168.98.22:8761/eureka/,http://192.168.98.23:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
      defaultZone: http://localhost:8761/eureka/


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactvie: DEBUG
    reactor.ipc.netty: DEBUG
  config:
    classpath: logback.xml
