spring:
  application:
    name: hello-service
  #profiles: 192.168.98.23
server:
  port: 8888


eureka:
  instance:
    hostname: localhost
    #ip-address: localh
    prefer-ip-address: true
  client:
    serviceUrl:
      #defaultZone: http://192.168.98.22:8761/eureka/,http://192.168.98.23:8761/eureka/
      defaultZone:http://localhost:8761/eureka/,http://localhost:8762/eureka/
